"""
Yaw moment allocator using axle-first lateral force split.
"""

from dataclasses import dataclass
from typing import Dict, Mapping, Optional, Tuple


def distribute_lateral_force_basic(
    Fy_total: float,
    Mz_des: float,
    lf: float,
    lr: float,
) -> Dict[str, float]:
    """Split total lateral force and desired yaw moment into axle and wheel commands."""
    lf = float(lf)
    lr = float(lr)
    Fy_total = float(Fy_total)
    Mz_des = float(Mz_des)

    wheelbase = lf + lr
    if abs(wheelbase) < 1e-9:
        raise ValueError("lf + lr must be non-zero for lateral force distribution")

    Fy_f = (Mz_des + lr * Fy_total) / wheelbase
    Fy_r = (lf * Fy_total - Mz_des) / wheelbase

    return {
        "Fy_f": float(Fy_f),
        "Fy_r": float(Fy_r),
        "Fy_fl": float(Fy_f * 0.5),
        "Fy_fr": float(Fy_f * 0.5),
        "Fy_rl": float(Fy_r * 0.5),
        "Fy_rr": float(Fy_r * 0.5),
    }


@dataclass
class YawMomentAllocator:
    """Allocate per-wheel lateral forces for a desired yaw moment.

    Note:
        This allocator returns per-wheel lateral force commands in the wheel frame (Fy_wheel_cmd).
        It first splits Fy_total_cmd and the lateral portion of Mz_d into front/rear axle forces
        using lf/lr derived from corner geometry, then divides each axle evenly left/right.
        If axle-based allocation is unavailable, it falls back to the legacy equal per-wheel
        moment split.
    """

    min_abs_x: float = 1e-6

    @staticmethod
    def _resolve_corner_xy(vehicle_body, label: str) -> Tuple[float, float]:
        corner_xy = getattr(vehicle_body, "corner_xy", None)
        if isinstance(corner_xy, dict) and label in corner_xy:
            x_i, y_i = corner_xy[label]
            return float(x_i), float(y_i)

        params = getattr(vehicle_body, "params", None)
        params_corner_xy = getattr(params, "corner_xy", None)
        if isinstance(params_corner_xy, dict) and label in params_corner_xy:
            x_i, y_i = params_corner_xy[label]
            return float(x_i), float(y_i)

        signs = vehicle_body.corner_signs[label]
        x_i = (vehicle_body.params.L_wheelbase / 2.0) * signs["pitch"]
        y_i = (vehicle_body.params.L_track / 2.0) * signs["roll"]
        return float(x_i), float(y_i)

    @classmethod
    def _resolve_axle_distances(cls, vehicle_body) -> Tuple[float, float]:
        """Resolve front/rear axle distances from the vehicle corner geometry."""
        front_labels = [label for label in getattr(vehicle_body, "wheel_labels", []) if str(label).startswith("F")]
        rear_labels = [label for label in getattr(vehicle_body, "wheel_labels", []) if str(label).startswith("R")]

        if not front_labels or not rear_labels:
            raise ValueError("Axle-based lateral force distribution requires front and rear wheel labels")

        front_x = [abs(cls._resolve_corner_xy(vehicle_body, label)[0]) for label in front_labels]
        rear_x = [abs(cls._resolve_corner_xy(vehicle_body, label)[0]) for label in rear_labels]
        lf = sum(front_x) / len(front_x)
        lr = sum(rear_x) / len(rear_x)

        if lf < cls.min_abs_x or lr < cls.min_abs_x:
            raise ValueError("Wheelbase too small for axle-based yaw moment allocation")
        return float(lf), float(lr)

    @classmethod
    def _desired_lateral_moment(
        cls,
        vehicle_body,
        Mz_d: float,
        Fx_body: Optional[Mapping[str, float]],
    ) -> float:
        """Remove the yaw moment already generated by longitudinal tire forces."""
        if not Fx_body:
            return float(Mz_d)

        mz_from_fx = 0.0
        for label, Fx_i in Fx_body.items():
            if label not in getattr(vehicle_body, "wheel_labels", []):
                continue
            _, y_i = cls._resolve_corner_xy(vehicle_body, label)
            mz_from_fx += -float(y_i) * float(Fx_i)

        return float(Mz_d) - float(mz_from_fx)

    def _allocate_legacy(
        self,
        vehicle_body,
        Mz_d: float,
        Fx_body: Optional[Mapping[str, float]] = None,
        Fy_total_cmd: Optional[float] = None,
    ) -> Dict[str, float]:
        """Fallback to the legacy equal per-wheel moment split."""
        labels = list(vehicle_body.wheel_labels)
        if not labels:
            return {}

        fx_map = Fx_body or {}
        fy_wheel_cmd: Dict[str, float] = {}
        fy_bias = float(Fy_total_cmd) / len(labels) if Fy_total_cmd is not None else 0.0
        Mz_i = float(Mz_d) / len(labels)

        for label in labels:
            x_i, y_i = self._resolve_corner_xy(vehicle_body, label)
            if abs(x_i) < self.min_abs_x:
                raise ValueError("Wheelbase too small for yaw moment allocation")
            Fx_i = float(fx_map.get(label, 0.0))
            fy_wheel_cmd[label] = (Mz_i + y_i * Fx_i) / x_i + fy_bias

        return fy_wheel_cmd

    def allocate(
        self,
        vehicle_body,
        Mz_d: float,
        Fx_body: Optional[Dict[str, float]] = None,
        Fy_total_cmd: Optional[float] = None,
    ) -> Dict[str, float]:
        """
        Args:
            vehicle_body: VehicleBody instance (geometry + wheel labels).
            Mz_d: desired yaw moment about CG [N*m], body frame.
            Fx_body: optional per-wheel longitudinal forces [N] in body frame.
            Fy_total_cmd: optional total lateral force command [N] in body frame.

        Returns:
            per-wheel lateral force commands Fy_wheel_cmd [N] in wheel frame.
        """
        labels = list(vehicle_body.wheel_labels)
        if not labels:
            return {}

        fy_total = float(Fy_total_cmd) if Fy_total_cmd is not None else 0.0
        mz_lateral_des = self._desired_lateral_moment(vehicle_body, Mz_d, Fx_body)

        required_labels = {"FL", "FR", "RL", "RR"}
        if not required_labels.issubset(labels):
            return self._allocate_legacy(
                vehicle_body=vehicle_body,
                Mz_d=Mz_d,
                Fx_body=Fx_body,
                Fy_total_cmd=Fy_total_cmd,
            )

        lf, lr = self._resolve_axle_distances(vehicle_body)
        distributed = distribute_lateral_force_basic(
            Fy_total=fy_total,
            Mz_des=mz_lateral_des,
            lf=lf,
            lr=lr,
        )
        axle_map = {
            "FL": float(distributed["Fy_fl"]),
            "FR": float(distributed["Fy_fr"]),
            "RL": float(distributed["Fy_rl"]),
            "RR": float(distributed["Fy_rr"]),
        }
        return {label: float(axle_map.get(label, 0.0)) for label in labels}
